DROP TABLE messages IF EXISTS;
DROP TABLE users_chats IF EXISTS;
DROP TABLE comments IF EXISTS;
DROP TABLE photographs IF EXISTS;
DROP TABLE credit_cards IF EXISTS;
DROP TABLE roles_users IF EXISTS;
DROP TABLE roles IF EXISTS;
DROP TABLE advertisements IF EXISTS;
DROP TABLE categories IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE addresses IF EXISTS;
DROP TABLE countries IF EXISTS;
DROP TABLE cities IF EXISTS;
DROP TABLE personal_info IF EXISTS;
DROP TABLE chats IF EXISTS;



DROP SEQUENCE ad_seq IF EXISTS;
DROP SEQUENCE user_seq IF EXISTS;
DROP SEQUENCE role_seq IF EXISTS;
DROP SEQUENCE country_seq IF EXISTS;
DROP SEQUENCE city_seq IF EXISTS;
DROP SEQUENCE chat_seq IF EXISTS;

CREATE SEQUENCE user_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE role_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE country_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE city_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE chat_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE ad_seq AS INTEGER START WITH 100000;



CREATE TABLE countries
(
    id   integer GENERATED BY DEFAULT AS SEQUENCE country_seq,
    name VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE cities
(
    id   integer GENERATED BY DEFAULT AS SEQUENCE city_seq,
    name text UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE addresses
(
    id           integer GENERATED BY DEFAULT AS SEQUENCE user_seq,
    country_id   integer NOT NULL,
    city_id      integer NOT NULL,
    post_index   integer NOT NULL,
    street       text    NOT NULL,
    number_house integer NOT NULL,
    number_flat  integer,
    PRIMARY KEY (id),
    FOREIGN KEY (country_id) REFERENCES countries (id),
    FOREIGN KEY (city_id) REFERENCES cities (id)
);

CREATE TABLE personal_info
(
    id            integer GENERATED BY DEFAULT AS SEQUENCE user_seq,
    first_name    text      NOT NULL,
    last_name     text      NOT NULL,
    date_birthday timestamp NOT NULL,
    number_phone  integer   NOT NULL,
    sex           text      NOT NULL,
    PRIMARY KEY (id),
    CHECK (sex IN ('FEMALE', 'MALE'))
);

CREATE TABLE users
(
    id               integer   GENERATED BY DEFAULT AS SEQUENCE user_seq,
    login            text                    NOT NULL,
    password         text                    NOT NULL,
    rating           integer   DEFAULT 100    NOT NULL,
    enabled          boolean      DEFAULT true  NOT NULL,
    date_registered  timestamp DEFAULT now() NOT NULL,
    address_id       integer,
    personal_info_id integer,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE,
    FOREIGN KEY (personal_info_id) REFERENCES personal_info (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX users_unique_login_idx ON users (login);

CREATE TABLE roles
(
    id        integer GENERATED BY DEFAULT AS SEQUENCE role_seq,
    name_role text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE roles_users
(
    user_id integer,
    role_id integer,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE credit_cards
(
    id      integer GENERATED BY DEFAULT AS SEQUENCE user_seq,
    user_id integer NOT NULL,
    type    text    NOT NULL,
    number  DECIMAL NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE categories
(
    id       integer GENERATED BY DEFAULT AS SEQUENCE ad_seq,
    category text,
    PRIMARY KEY (id)
);


CREATE TABLE advertisements
(
    id                   integer GENERATED BY DEFAULT AS SEQUENCE ad_seq,
    title                text           NOT NULL,
    content              text           NOT NULL,
    cost                 decimal(10, 2) NOT NULL,
    date_publication     timestamp DEFAULT now(),
    date_publication_off timestamp,
    status               text      DEFAULT 'NEW',
    user_id              integer,
    category_id          integer,
    top_rating           boolean      DEFAULT false,
    date_top_off         timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE photographs
(
    id    integer GENERATED BY DEFAULT AS SEQUENCE ad_seq,
    ad_id integer NOT NULL,
    path  text    NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (ad_id) REFERENCES advertisements (id) ON DELETE CASCADE
);

CREATE TABLE comments
(
    id               integer GENERATED BY DEFAULT AS SEQUENCE ad_seq,
    ad_id            integer NOT NULL,
    user_id          integer NOT NULL,
    content          text    NOT NULL,
    date_publication timestamp DEFAULT now(),
    PRIMARY KEY (id),
    FOREIGN KEY (ad_id) REFERENCES advertisements (id) ON DELETE CASCADE ,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE

);

CREATE TABLE chats
(
    id   integer GENERATED BY DEFAULT AS SEQUENCE chat_seq,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE users_chats
(
    chat_id integer NOT NULL,
    user_id integer NOT NULL,
    FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE messages
(
    id          integer GENERATED BY DEFAULT AS SEQUENCE chat_seq,
    user_id     integer NOT NULL,
    chat_id     integer NOT NULL,
    content     text    NOT NULL,
    date_create timestamp DEFAULT now(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ,
    FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE
);